title: 
description: 
# baseurl: "/msky"
baseurl: "/"
url: "https://jasonmin.github.io"

# 构建设置
markdown: kramdown
# theme: minima
# theme: jekyll-theme-minimal
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - zzcommit.sh
  - README.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      encoding: utf-8 